[incus_nodes]
node-control ansible_host=node-control
app-api ansible_host=app-api
app-core ansible_host=app-core
db-postgres ansible_host=db-postgres
monitoring ansible_host=monitoring
ceph-node ansible_host=ceph-node

[api]
app-api

[core]
app-core

[database]
db-postgres

[monitoring]
monitoring

[storage]
ceph-node
